// AUTOGENERATED by scripts/transform-data.cjs — nested weeks (all weeks)
// Run scripts/transform-data.cjs to regenerate

import { Week } from "@/lib/types";

export const weeksNested: Week[] = [
  {
    id: "week-06",
    startDate: "2026-02-02",
    endDate: "2026-02-08",
    title: "Moses 7: The Lord Called His People Zion",
    lessonUrl:
      "https://www.churchofjesuschrist.org/study/manual/come-follow-me-for-home-and-church-old-testament-2026/06",
    scriptures: [
      {
        reference: "Moses 7",
        url: "https://www.churchofjesuschrist.org/study/scriptures/pgp/moses/7",
      },
    ],
    days: [
      {
        id: "week-06-day-1",
        date: "2026-02-02",
        doctrine: {
          doctrine: "The Lord Strengthens Those He Calls",
          summary:
            "Enoch felt inadequate, but the Lord empowered him to fulfill his calling.",
          explanation:
            "Moses 7 shows that Enoch, once slow of speech and unsure of himself, became a mighty prophet because the Lord strengthened him. God often calls the humble and enables them to do His work.",
          references: [],
          scriptures: [
            {
              reference: "Moses 7:13",
              url: "https://www.churchofjesuschrist.org/study/scriptures/pgp/moses/7.13",
            },
          ],
        },
        scripturePassage: {
          reference: {
            reference: "Moses 7:13",
            url: "https://www.churchofjesuschrist.org/study/scriptures/pgp/moses/7.13",
          },
          text: "A summary of Enoch’s God-given power, including moving mountains and defeating enemies through the Lord’s strength.",
          context:
            "Enoch’s transformation demonstrates that God magnifies those He calls.",
          historicalBackground:
            "Ancient traditions often portrayed prophets as empowered by divine authority; Moses 7 emphasizes this theme strongly.",
          citations: [],
        },
        word: {
          id: "week-06-day-1-word",
          date: "2026-02-02",
          weekTitle: "The Lord Called His People Zion",
          word: "Endow",
          definition: "To provide with power or capacity from God.",
          context:
            "Enoch was endowed with divine power to fulfill his calling.",
          scriptures: [
            {
              reference: "Moses 7:13",
              url: "https://www.churchofjesuschrist.org/study/scriptures/pgp/moses/7.13",
            },
          ],
        },
        questions: [
          {
            scriptureReference: {
              reference: "Moses 7:13",
              url: "https://www.churchofjesuschrist.org/study/scriptures/pgp/moses/7.13",
            },
            lessonUrl:
              "https://www.churchofjesuschrist.org/study/manual/come-follow-me-for-home-and-church-old-testament-2026/06",
            question:
              "What does Enoch’s experience teach about God’s pattern in calling His servants?",
            options: [
              "He strengthens the humble to accomplish His work.",
              "He only calls those who are already powerful.",
              "He avoids calling those who feel inadequate.",
              "He expects people to succeed without His help.",
            ],
            correctAnswer: 0,
            explanation:
              "Enoch’s story shows that God empowers those He calls, regardless of their natural abilities.",
            references: [],
          },
        ],
      },

      {
        id: "week-06-day-2",
        date: "2026-02-03",
        doctrine: {
          doctrine: "The Lord Knows His People",
          summary:
            "God sees all nations and is aware of their righteousness and wickedness.",
          explanation:
            "Moses 7 describes Enoch’s panoramic vision of the world. The Lord shows that He is aware of every people and every land, and His work extends to all His children.",
          references: [],
          scriptures: [
            {
              reference: "Moses 7:21–23",
              url: "https://www.churchofjesuschrist.org/study/scriptures/pgp/moses/7.21-23",
            },
          ],
        },
        scripturePassage: {
          reference: {
            reference: "Moses 7:21–23",
            url: "https://www.churchofjesuschrist.org/study/scriptures/pgp/moses/7.21-23",
          },
          text: "A summary of Enoch seeing the land of Zion lifted up and the Lord’s awareness of all nations.",
          context:
            "Enoch’s vision reveals God’s omniscience and care for His covenant people.",
          historicalBackground:
            "Prophetic visions of the world were common in ancient writings, symbolizing divine perspective.",
          citations: [],
        },
        word: {
          id: "week-06-day-2-word",
          date: "2026-02-03",
          weekTitle: "The Lord Called His People Zion",
          word: "Omniscient",
          definition:
            "All-knowing; aware of all things past, present, and future.",
          context: "God shows Enoch that He knows all nations and peoples.",
          scriptures: [
            {
              reference: "Moses 7:23",
              url: "https://www.churchofjesuschrist.org/study/scriptures/pgp/moses/7.23",
            },
          ],
        },
        questions: [
          {
            scriptureReference: {
              reference: "Moses 7:21–23",
              url: "https://www.churchofjesuschrist.org/study/scriptures/pgp/moses/7.21-23",
            },
            lessonUrl:
              "https://www.churchofjesuschrist.org/study/manual/come-follow-me-for-home-and-church-old-testament-2026/06",
            question:
              "What does Enoch’s vision teach about God’s relationship with His children?",
            options: [
              "He knows all nations and cares for all His children.",
              "He is only aware of a few chosen people.",
              "He is distant and uninvolved.",
              "He only watches the righteous.",
            ],
            correctAnswer: 0,
            explanation:
              "The vision shows God’s awareness of all peoples and His involvement in their lives.",
            references: [],
          },
        ],
      },

      {
        id: "week-06-day-3",
        date: "2026-02-04",
        doctrine: {
          doctrine: "Zion Is a People of One Heart and One Mind",
          summary:
            "The people of Enoch became Zion because they were unified in righteousness.",
          explanation:
            "Moses 7 teaches that Zion is not just a place but a condition of the heart. Enoch’s people were of ‘one heart and one mind,’ dwelling in righteousness with no poor among them.",
          references: [],
          scriptures: [
            {
              reference: "Moses 7:18",
              url: "https://www.churchofjesuschrist.org/study/scriptures/pgp/moses/7.18",
            },
          ],
        },
        scripturePassage: {
          reference: {
            reference: "Moses 7:18",
            url: "https://www.churchofjesuschrist.org/study/scriptures/pgp/moses/7.18",
          },
          text: "A summary of the characteristics of Zion: unity, righteousness, and care for the poor.",
          context:
            "This verse is central to understanding the Lord’s pattern for building Zion.",
          historicalBackground:
            "Ancient Israelite ideals of community emphasized justice, unity, and care for the vulnerable.",
          citations: [],
        },
        word: {
          id: "week-06-day-3-word",
          date: "2026-02-04",
          weekTitle: "The Lord Called His People Zion",
          word: "Zion",
          definition:
            "A people who are pure in heart, unified, and living God’s laws.",
          context:
            "Enoch’s people became Zion through righteousness and unity.",
          scriptures: [
            {
              reference: "Moses 7:18",
              url: "https://www.churchofjesuschrist.org/study/scriptures/pgp/moses/7.18",
            },
          ],
        },
        questions: [
          {
            scriptureReference: {
              reference: "Moses 7:18",
              url: "https://www.churchofjesuschrist.org/study/scriptures/pgp/moses/7.18",
            },
            lessonUrl:
              "https://www.churchofjesuschrist.org/study/manual/come-follow-me-for-home-and-church-old-testament-2026/06",
            question:
              "What key characteristic made Enoch’s people a Zion people?",
            options: [
              "They were of one heart and one mind.",
              "They were wealthy and powerful.",
              "They lived far away from other nations.",
              "They had no trials.",
            ],
            correctAnswer: 0,
            explanation:
              "Unity in righteousness is the defining feature of Zion.",
            references: [],
          },
        ],
      },

      {
        id: "week-06-day-4",
        date: "2026-02-05",
        doctrine: {
          doctrine: "The Lord Weeps for His Children",
          summary: "God feels sorrow when His children choose wickedness.",
          explanation:
            "In Moses 7, Enoch is surprised to see God weep. The Lord explains that His sorrow comes from the suffering His children bring upon themselves through sin.",
          references: [],
          scriptures: [
            {
              reference: "Moses 7:28–33",
              url: "https://www.churchofjesuschrist.org/study/scriptures/pgp/moses/7.28-33",
            },
          ],
        },
        scripturePassage: {
          reference: {
            reference: "Moses 7:28–33",
            url: "https://www.churchofjesuschrist.org/study/scriptures/pgp/moses/7.28-33",
          },
          text: "A summary of Enoch witnessing God weep over the wickedness and suffering of His children.",
          context:
            "This passage reveals God’s deep compassion and emotional investment in His children.",
          historicalBackground:
            "Depictions of divine emotion were rare in ancient texts; Moses 7 uniquely portrays God’s empathy.",
          citations: [],
        },
        word: {
          id: "week-06-day-4-word",
          date: "2026-02-05",
          weekTitle: "The Lord Called His People Zion",
          word: "Compassion",
          definition: "Deep sympathy and concern for the suffering of others.",
          context: "God weeps because of His compassion for His children.",
          scriptures: [
            {
              reference: "Moses 7:28",
              url: "https://www.churchofjesuschrist.org/study/scriptures/pgp/moses/7.28",
            },
          ],
        },
        questions: [
          {
            scriptureReference: {
              reference: "Moses 7:28–33",
              url: "https://www.churchofjesuschrist.org/study/scriptures/pgp/moses/7.28-33",
            },
            lessonUrl:
              "https://www.churchofjesuschrist.org/study/manual/come-follow-me-for-home-and-church-old-testament-2026/06",
            question: "Why does God weep in Moses 7?",
            options: [
              "Because His children suffer due to their choices.",
              "Because He lacks power to help.",
              "Because He is surprised by wickedness.",
              "Because He is distant from humanity.",
            ],
            correctAnswer: 0,
            explanation:
              "God’s sorrow reflects His love and compassion for His children.",
            references: [],
          },
        ],
      },

      {
        id: "week-06-day-5",
        date: "2026-02-06",
        doctrine: {
          doctrine: "The Lord Will Ultimately Triumph Over Evil",
          summary:
            "Enoch sees the eventual victory of righteousness over wickedness.",
          explanation:
            "Moses 7 includes visions of future events, showing that despite periods of great wickedness, God’s plan will prevail and Zion will return.",
          references: [],
          scriptures: [
            {
              reference: "Moses 7:44–47",
              url: "https://www.churchofjesuschrist.org/study/scriptures/pgp/moses/7.44-47",
            },
          ],
        },
        scripturePassage: {
          reference: {
            reference: "Moses 7:44–47",
            url: "https://www.churchofjesuschrist.org/study/scriptures/pgp/moses/7.44-47",
          },
          text: "A summary of Enoch seeing the Savior’s mortal ministry and the triumph of righteousness.",
          context: "Enoch’s vision spans from his day to the coming of Christ.",
          historicalBackground:
            "Prophetic visions often connected past, present, and future to show God’s overarching plan.",
          citations: [],
        },
        word: {
          id: "week-06-day-5-word",
          date: "2026-02-06",
          weekTitle: "The Lord Called His People Zion",
          word: "Redeemer",
          definition: "One who delivers or saves; a title for Jesus Christ.",
          context: "Enoch sees the Redeemer and rejoices.",
          scriptures: [
            {
              reference: "Moses 7:47",
              url: "https://www.churchofjesuschrist.org/study/scriptures/pgp/moses/7.47",
            },
          ],
        },
        questions: [
          {
            scriptureReference: {
              reference: "Moses 7:44–47",
              url: "https://www.churchofjesuschrist.org/study/scriptures/pgp/moses/7.44-47",
            },
            lessonUrl:
              "https://www.churchofjesuschrist.org/study/manual/come-follow-me-for-home-and-church-old-testament-2026/06",
            question: "What does Enoch’s vision teach about the Savior?",
            options: [
              "He will redeem and comfort God’s children.",
              "He will only save a select few.",
              "He is uninvolved in human suffering.",
              "He will not triumph over evil.",
            ],
            correctAnswer: 0,
            explanation:
              "Enoch rejoices in seeing the Redeemer’s mission and ultimate victory.",
            references: [],
          },
        ],
      },

      {
        id: "week-06-day-6",
        date: "2026-02-07",
        doctrine: {
          doctrine: "Zion Will Return in the Last Days",
          summary:
            "Enoch sees that his city will return and join with the righteous on earth.",
          explanation:
            "Moses 7 teaches that the City of Enoch will return during the Millennium, joining with a latter-day Zion prepared by the Saints.",
          references: [],
          scriptures: [
            {
              reference: "Moses 7:62–64",
              url: "https://www.churchofjesuschrist.org/study/scriptures/pgp/moses/7.62-64",
            },
          ],
        },
        scripturePassage: {
          reference: {
            reference: "Moses 7:62–64",
            url: "https://www.churchofjesuschrist.org/study/scriptures/pgp/moses/7.62-64",
          },
          text: "A summary of the prophecy that Zion will return and righteousness will prevail in the last days.",
          context:
            "The Lord promises a great latter-day gathering and unity between heaven and earth.",
          historicalBackground:
            "Restoration teachings emphasize the return of Zion as part of the Millennium.",
          citations: [],
        },
        word: {
          id: "week-06-day-6-word",
          date: "2026-02-07",
          weekTitle: "The Lord Called His People Zion",
          word: "Millennium",
          definition:
            "A thousand-year period of peace when Christ will reign personally on the earth.",
          context: "Zion’s return is associated with the Millennium.",
          scriptures: [
            {
              reference: "Moses 7:64",
              url: "https://www.churchofjesuschrist.org/study/scriptures/pgp/moses/7.64",
            },
          ],
        },
        questions: [
          {
            scriptureReference: {
              reference: "Moses 7:62–64",
              url: "https://www.churchofjesuschrist.org/study/scriptures/pgp/moses/7.62-64",
            },
            lessonUrl:
              "https://www.churchofjesuschrist.org/study/manual/come-follow-me-for-home-and-church-old-testament-2026/06",
            question: "What future event does the Lord promise in Moses 7?",
            options: [
              "The return of Zion and a great gathering of the righteous.",
              "The end of all covenants.",
              "The destruction of all nations.",
              "The disappearance of the earth.",
            ],
            correctAnswer: 0,
            explanation:
              "The Lord promises that Zion will return and unite with a latter-day Zion.",
            references: [],
          },
        ],
      },

      {
        id: "week-06-day-7",
        date: "2026-02-08",
        doctrine: {
          doctrine: "The Lord Will Dwell with His People",
          summary:
            "The City of Enoch was taken up because the people lived in perfect harmony with God.",
          explanation:
            "Moses 7 concludes with the Lord receiving Zion into His own bosom. This teaches that when a people fully embrace righteousness, unity, and charity, they become prepared to dwell in the presence of God.",
          references: [],
          scriptures: [
            {
              reference: "Moses 7:69",
              url: "https://www.churchofjesuschrist.org/study/scriptures/pgp/moses/7.69",
            },
          ],
        },
        scripturePassage: {
          reference: {
            reference: "Moses 7:69",
            url: "https://www.churchofjesuschrist.org/study/scriptures/pgp/moses/7.69",
          },
          text: "A summary of Zion being taken up into heaven because of their righteousness and unity.",
          context:
            "This verse marks the culmination of Enoch’s ministry and the transformation of his people into a celestial society.",
          historicalBackground:
            "Ancient traditions about Enoch often portray him as ascending to heaven; the Pearl of Great Price uniquely describes an entire city being translated.",
          citations: [],
        },
        word: {
          id: "week-06-day-7-word",
          date: "2026-02-08",
          weekTitle: "The Lord Called His People Zion",
          word: "Translate",
          definition:
            "To be changed so as not to experience death, remaining in a state of immortality until the resurrection.",
          context:
            "The City of Enoch was translated because of their righteousness.",
          scriptures: [
            {
              reference: "Moses 7:69",
              url: "https://www.churchofjesuschrist.org/study/scriptures/pgp/moses/7.69",
            },
          ],
        },
        questions: [
          {
            scriptureReference: {
              reference: "Moses 7:69",
              url: "https://www.churchofjesuschrist.org/study/scriptures/pgp/moses/7.69",
            },
            lessonUrl:
              "https://www.churchofjesuschrist.org/study/manual/come-follow-me-for-home-and-church-old-testament-2026/06",
            question: "Why was the City of Enoch taken up into heaven?",
            options: [
              "Because the people lived in perfect unity and righteousness.",
              "Because they were the wealthiest people on earth.",
              "Because they fled from their enemies.",
              "Because they wished to avoid responsibility.",
            ],
            correctAnswer: 0,
            explanation:
              "The people of Enoch became Zion—pure in heart, unified, and living God’s laws—making them prepared to dwell with the Lord.",
            references: [],
          },
        ],
      },
    ],
    places: [
      {
        name: "Zion",
        modernLocation: "Unknown; described as being taken up into heaven",
        locationType: "symbolic",
        description:
          "The city of Enoch, whose people were of one heart and one mind and dwelt in righteousness. Because of their holiness, the entire city was translated.",
        scriptureReferences: [
          {
            reference: "Moses 7:18–21",
            url: "https://www.churchofjesuschrist.org/study/scriptures/pgp/moses/7.18-21",
          },
        ],
        citations: [],
      },
      {
        name: "Mount Simeon",
        modernLocation: "Uncertain",
        locationType: "uncertain",
        description:
          "A location mentioned in Enoch’s ministry where he stood and preached repentance to the people.",
        scriptureReferences: [
          {
            reference: "Moses 7:2",
            url: "https://www.churchofjesuschrist.org/study/scriptures/pgp/moses/7.2",
          },
        ],
        citations: [],
      },
      {
        name: "The Bosom of the Father",
        modernLocation: "Symbolic",
        locationType: "symbolic",
        description:
          "A symbolic expression representing the presence, protection, and glory of God. Zion was received into the bosom of the Father.",
        scriptureReferences: [
          {
            reference: "Moses 7:69",
            url: "https://www.churchofjesuschrist.org/study/scriptures/pgp/moses/7.69",
          },
        ],
        citations: [],
      },
      {
        name: "The Earth (in vision)",
        modernLocation: "Global",
        locationType: "symbolic",
        description:
          "Enoch sees the earth in vision, including its wickedness, suffering, and future redemption. The earth itself weeps in sorrow.",
        scriptureReferences: [
          {
            reference: "Moses 7:48–49",
            url: "https://www.churchofjesuschrist.org/study/scriptures/pgp/moses/7.48-49",
          },
        ],
        citations: [],
      },
    ],
    people: [
      {
        name: "Enoch",
        role: "Prophet and leader of Zion",
        description:
          "A prophet called by God to preach repentance, perform miracles, receive visions of past and future, and lead a people who became so righteous they were taken into heaven.",
        scriptureReferences: [
          {
            reference: "Moses 7",
            url: "https://www.churchofjesuschrist.org/study/scriptures/pgp/moses/7",
          },
        ],
        citations: [],
      },
      {
        name: "The People of Zion",
        role: "Covenant community",
        description:
          "A society led by Enoch that became unified, righteous, and without poor among them. Because of their holiness, they were taken up into heaven.",
        scriptureReferences: [
          {
            reference: "Moses 7:18–21",
            url: "https://www.churchofjesuschrist.org/study/scriptures/pgp/moses/7.18-21",
          },
        ],
        citations: [],
      },
      {
        name: "The Lord",
        role: "God; the Eternal Father",
        description:
          "Reveals visions to Enoch, expresses compassion for His children, establishes covenants, and promises the eventual triumph of righteousness.",
        scriptureReferences: [
          {
            reference: "Moses 7:28–33",
            url: "https://www.churchofjesuschrist.org/study/scriptures/pgp/moses/7.28-33",
          },
        ],
        citations: [],
      },
      {
        name: "The Son of Man (Jesus Christ)",
        role: "Redeemer",
        description:
          "Shown to Enoch in vision, weeping for the wicked and later triumphing over death and sin. His mission is central to God’s plan.",
        scriptureReferences: [
          {
            reference: "Moses 7:47",
            url: "https://www.churchofjesuschrist.org/study/scriptures/pgp/moses/7.47",
          },
        ],
        citations: [],
      },
    ],
  },
  {
    id: "week-07",
    startDate: "2026-02-09",
    endDate: "2026-02-15",
    title: "Genesis 6–11; Moses 8: The Covenant",
    lessonUrl:
      "https://www.churchofjesuschrist.org/study/manual/come-follow-me-for-home-and-church-old-testament-2026/07",
    scriptures: [
      {
        reference: "Genesis 6",
        url: "https://www.churchofjesuschrist.org/study/scriptures/ot/gen/6",
      },
      {
        reference: "Genesis 7",
        url: "https://www.churchofjesuschrist.org/study/scriptures/ot/gen/7",
      },
      {
        reference: "Genesis 8",
        url: "https://www.churchofjesuschrist.org/study/scriptures/ot/gen/8",
      },
      {
        reference: "Genesis 9",
        url: "https://www.churchofjesuschrist.org/study/scriptures/ot/gen/9",
      },
      {
        reference: "Genesis 10",
        url: "https://www.churchofjesuschrist.org/study/scriptures/ot/gen/10",
      },
      {
        reference: "Genesis 11",
        url: "https://www.churchofjesuschrist.org/study/scriptures/ot/gen/11",
      },
      {
        reference: "Moses 8",
        url: "https://www.churchofjesuschrist.org/study/scriptures/pgp/moses/8",
      },
    ],
    days: [
      {
        id: "week-07-day-1",
        date: "2026-02-09",
        doctrine: {
          doctrine: "God Calls the Righteous to Warn the World",
          summary:
            "Noah was called to preach repentance in a time of great wickedness.",
          explanation:
            "Moses 8 and Genesis 6 show that before the Flood, the Lord called Noah as a prophet to warn the people. His example teaches that God always sends prophets before judgments and that disciples are invited to stand as witnesses even when few listen.",
          references: [
            {
              display: "Moses 8:19–24",
              url: "https://www.churchofjesuschrist.org/study/scriptures/pgp/moses/8.19-24",
            },
          ],
          scriptures: [
            {
              reference: "Genesis 6:5–9",
              url: "https://www.churchofjesuschrist.org/study/scriptures/ot/gen/6.5-9",
            },
          ],
        },
        scripturePassage: {
          reference: {
            reference: "Moses 8:19–24",
            url: "https://www.churchofjesuschrist.org/study/scriptures/pgp/moses/8.19-24",
          },
          text: "A summary of Noah’s preaching of repentance and the people’s rejection of his message.",
          context:
            "Noah is described as a just man who walked with God and was commanded to cry repentance to a corrupt generation.",
          historicalBackground:
            "In ancient tradition, righteous patriarchs were seen as mediators between God and their communities, responsible to warn and teach.",
          citations: [],
        },
        word: {
          id: "week-07-day-1-word",
          date: "2026-02-09",
          weekTitle: "The Covenant",
          word: "Preach",
          definition: "To declare or proclaim God’s word by commandment.",
          context:
            "Noah was commanded to preach repentance to the people before the Flood.",
          scriptures: [
            {
              reference: "Moses 8:19",
              url: "https://www.churchofjesuschrist.org/study/scriptures/pgp/moses/8.19",
            },
          ],
        },
        questions: [
          {
            scriptureReference: {
              reference: "Moses 8:19–24",
              url: "https://www.churchofjesuschrist.org/study/scriptures/pgp/moses/8.19-24",
            },
            lessonUrl:
              "https://www.churchofjesuschrist.org/study/manual/come-follow-me-for-home-and-church-old-testament-2026/07",
            question:
              "What does Noah’s example teach about our responsibility when we know God’s will?",
            options: [
              "We should warn and invite others, even if few listen.",
              "We should keep spiritual things private.",
              "We are only responsible for ourselves.",
              "We should wait until others ask us first.",
            ],
            correctAnswer: 0,
            explanation:
              "Noah’s ministry shows that disciples are called to testify and invite, regardless of how many accept the message.",
            references: [],
          },
        ],
      },
      {
        id: "week-07-day-2",
        date: "2026-02-10",
        doctrine: {
          doctrine: "God Commands Us to Build Spiritual Arks",
          summary:
            "Noah’s ark symbolizes preparation and obedience in times of spiritual danger.",
          explanation:
            "Genesis 6 records that God commanded Noah to build an ark as protection from the coming Flood. Today, we build spiritual ‘arks’ through covenants, obedience, and daily discipleship that protect us from spiritual storms.",
          references: [],
          scriptures: [
            {
              reference: "Genesis 6:13–22",
              url: "https://www.churchofjesuschrist.org/study/scriptures/ot/gen/6.13-22",
            },
          ],
        },
        scripturePassage: {
          reference: {
            reference: "Genesis 6:13–22",
            url: "https://www.churchofjesuschrist.org/study/scriptures/ot/gen/6.13-22",
          },
          text: "A summary of God’s command to Noah to build an ark and Noah’s exact obedience.",
          context:
            "Noah follows detailed instructions from the Lord to prepare for the Flood.",
          historicalBackground:
            "Ancient flood narratives exist in several cultures, but Genesis emphasizes obedience to the one true God rather than conflict among gods.",
          citations: [],
        },
        word: {
          id: "week-07-day-2-word",
          date: "2026-02-10",
          weekTitle: "The Covenant",
          word: "Ark",
          definition:
            "A vessel of preservation; a place of safety prepared by God’s command.",
          context:
            "Noah’s ark preserved life during the Flood and symbolizes spiritual refuge.",
          scriptures: [
            {
              reference: "Genesis 6:14",
              url: "https://www.churchofjesuschrist.org/study/scriptures/ot/gen/6.14",
            },
          ],
        },
        questions: [
          {
            scriptureReference: {
              reference: "Genesis 6:13–22",
              url: "https://www.churchofjesuschrist.org/study/scriptures/ot/gen/6.13-22",
            },
            lessonUrl:
              "https://www.churchofjesuschrist.org/study/manual/come-follow-me-for-home-and-church-old-testament-2026/07",
            question:
              "How did Noah respond to the Lord’s command to build the ark?",
            options: [
              "He did according to all that God commanded him.",
              "He delayed until the rain began.",
              "He asked for a different assignment.",
              "He refused because it seemed unreasonable.",
            ],
            correctAnswer: 0,
            explanation:
              "Noah’s exact obedience is emphasized as a model of faith and trust in God.",
            references: [],
          },
        ],
      },
      {
        id: "week-07-day-3",
        date: "2026-02-11",
        doctrine: {
          doctrine: "The Lord Remembers His Covenants in Times of Trial",
          summary:
            "During the Flood, God remembered Noah and all that were with him in the ark.",
          explanation:
            "Genesis 7–8 shows that even amid destruction and uncertainty, the Lord remembered Noah. This teaches that God does not forget those who have entered into covenants with Him, even when circumstances feel overwhelming.",
          references: [],
          scriptures: [
            {
              reference: "Genesis 7:17–24",
              url: "https://www.churchofjesuschrist.org/study/scriptures/ot/gen/7.17-24",
            },
            {
              reference: "Genesis 8:1",
              url: "https://www.churchofjesuschrist.org/study/scriptures/ot/gen/8.1",
            },
          ],
        },
        scripturePassage: {
          reference: {
            reference: "Genesis 8:1–12",
            url: "https://www.churchofjesuschrist.org/study/scriptures/ot/gen/8.1-12",
          },
          text: "A summary of the waters receding, the ark resting, and Noah sending out birds to see if the earth was dry.",
          context:
            "After many days on the ark, Noah seeks to know when it is safe to leave.",
          historicalBackground:
            "Doves and ravens were common symbols in ancient Near Eastern literature; here they serve as practical signs of changing conditions.",
          citations: [],
        },
        word: {
          id: "week-07-day-3-word",
          date: "2026-02-11",
          weekTitle: "The Covenant",
          word: "Remember",
          definition:
            "In scripture, to remember often means to act in faithfulness to a covenant.",
          context:
            "God ‘remembered’ Noah, meaning He acted to fulfill His promises.",
          scriptures: [
            {
              reference: "Genesis 8:1",
              url: "https://www.churchofjesuschrist.org/study/scriptures/ot/gen/8.1",
            },
          ],
        },
        questions: [
          {
            scriptureReference: {
              reference: "Genesis 8:1–12",
              url: "https://www.churchofjesuschrist.org/study/scriptures/ot/gen/8.1-12",
            },
            lessonUrl:
              "https://www.churchofjesuschrist.org/study/manual/come-follow-me-for-home-and-church-old-testament-2026/07",
            question: "What does it mean that ‘God remembered Noah’?",
            options: [
              "God acted to fulfill His covenant with Noah.",
              "God had forgotten Noah for a time.",
              "God was surprised by the Flood.",
              "God changed His plan midway.",
            ],
            correctAnswer: 0,
            explanation:
              "In scripture, God ‘remembering’ often means He is actively keeping His covenant promises.",
            references: [],
          },
        ],
      },
      {
        id: "week-07-day-4",
        date: "2026-02-12",
        doctrine: {
          doctrine: "God Establishes Covenants with His Children",
          summary:
            "After the Flood, God made a covenant with Noah and his posterity.",
          explanation:
            "Genesis 9 describes God’s covenant with Noah, including promises of preservation and the sign of the rainbow. This covenant points to God’s desire to bind Himself to His children through sacred promises.",
          references: [],
          scriptures: [
            {
              reference: "Genesis 9:8–17",
              url: "https://www.churchofjesuschrist.org/study/scriptures/ot/gen/9.8-17",
            },
          ],
        },
        scripturePassage: {
          reference: {
            reference: "Genesis 9:8–17",
            url: "https://www.churchofjesuschrist.org/study/scriptures/ot/gen/9.8-17",
          },
          text: "A summary of God’s covenant with Noah and the sign of the rainbow.",
          context:
            "God promises never again to destroy all flesh with a flood and sets the bow in the cloud as a token.",
          historicalBackground:
            "Rainbows were seen in many cultures as divine signs; in Genesis, the rainbow is explicitly tied to God’s covenant mercy.",
          citations: [],
        },
        word: {
          id: "week-07-day-4-word",
          date: "2026-02-12",
          weekTitle: "The Covenant",
          word: "Token",
          definition: "A sign or symbol that represents a covenant or promise.",
          context:
            "The rainbow is called a token of the covenant between God and the earth.",
          scriptures: [
            {
              reference: "Genesis 9:13",
              url: "https://www.churchofjesuschrist.org/study/scriptures/ot/gen/9.13",
            },
          ],
        },
        questions: [
          {
            scriptureReference: {
              reference: "Genesis 9:8–17",
              url: "https://www.churchofjesuschrist.org/study/scriptures/ot/gen/9.8-17",
            },
            lessonUrl:
              "https://www.churchofjesuschrist.org/study/manual/come-follow-me-for-home-and-church-old-testament-2026/07",
            question:
              "What does the rainbow represent in God’s covenant with Noah?",
            options: [
              "A token of God’s promise of mercy.",
              "A sign that storms will never come again.",
              "A symbol of human power.",
              "A reminder that covenants are temporary.",
            ],
            correctAnswer: 0,
            explanation:
              "The rainbow is a visible reminder of God’s covenant and His mercy toward His creations.",
            references: [],
          },
        ],
      },
      {
        id: "week-07-day-5",
        date: "2026-02-13",
        doctrine: {
          doctrine: "We Are All Part of God’s Family",
          summary:
            "The table of nations shows that all peoples trace back to God’s children after the Flood.",
          explanation:
            "Genesis 10 lists the descendants of Noah’s sons, emphasizing that the nations of the earth share a common origin. This supports the doctrine that all are alike unto God and that He is the Father of all spirits.",
          references: [],
          scriptures: [
            {
              reference: "Genesis 10",
              url: "https://www.churchofjesuschrist.org/study/scriptures/ot/gen/10",
            },
          ],
        },
        scripturePassage: {
          reference: {
            reference: "Genesis 10:1–5",
            url: "https://www.churchofjesuschrist.org/study/scriptures/ot/gen/10.1-5",
          },
          text: "A summary of the generations of Noah’s sons and the spreading of nations.",
          context:
            "These genealogies connect the story of the Flood to the broader human family.",
          historicalBackground:
            "Genealogies in the ancient world established identity, inheritance, and covenant lineage.",
          citations: [],
        },
        word: {
          id: "week-07-day-5-word",
          date: "2026-02-13",
          weekTitle: "The Covenant",
          word: "Generation",
          definition:
            "A group of people born and living around the same time; in scripture, often used to trace lineage.",
          context: "Genesis 10 traces the generations of Noah’s sons.",
          scriptures: [
            {
              reference: "Genesis 10:1",
              url: "https://www.churchofjesuschrist.org/study/scriptures/ot/gen/10.1",
            },
          ],
        },
        questions: [
          {
            scriptureReference: {
              reference: "Genesis 10:1–5",
              url: "https://www.churchofjesuschrist.org/study/scriptures/ot/gen/10.1-5",
            },
            lessonUrl:
              "https://www.churchofjesuschrist.org/study/manual/come-follow-me-for-home-and-church-old-testament-2026/07",
            question:
              "What truth is reinforced by the genealogies after the Flood?",
            options: [
              "All people are part of one human family under God.",
              "Some lineages are less valuable to God.",
              "Genealogy has no spiritual meaning.",
              "Only one nation matters to God.",
            ],
            correctAnswer: 0,
            explanation:
              "The record of nations descending from Noah emphasizes our shared divine origin.",
            references: [],
          },
        ],
      },
      {
        id: "week-07-day-6",
        date: "2026-02-14",
        doctrine: {
          doctrine: "Pride Leads to Confusion and Division",
          summary:
            "The Tower of Babel shows the consequences of seeking self-glory instead of God’s will.",
          explanation:
            "In Genesis 11, people unite to build a tower to ‘make a name’ for themselves. God confounds their language, illustrating that pride and rebellion lead to spiritual and social fragmentation.",
          references: [],
          scriptures: [
            {
              reference: "Genesis 11:1–9",
              url: "https://www.churchofjesuschrist.org/study/scriptures/ot/gen/11.1-9",
            },
          ],
        },
        scripturePassage: {
          reference: {
            reference: "Genesis 11:1–9",
            url: "https://www.churchofjesuschrist.org/study/scriptures/ot/gen/11.1-9",
          },
          text: "A summary of the people’s attempt to build the Tower of Babel and the Lord confounding their language.",
          context:
            "The people seek to build a city and tower to avoid being scattered and to glorify themselves.",
          historicalBackground:
            "Ziggurats—stepped temple towers—were common in Mesopotamia and may be reflected in the Babel story.",
          citations: [],
        },
        word: {
          id: "week-07-day-6-word",
          date: "2026-02-14",
          weekTitle: "The Covenant",
          word: "Confound",
          definition: "To mix up, confuse, or frustrate plans.",
          context: "God confounded the language of the people at Babel.",
          scriptures: [
            {
              reference: "Genesis 11:7",
              url: "https://www.churchofjesuschrist.org/study/scriptures/ot/gen/11.7",
            },
          ],
        },
        questions: [
          {
            scriptureReference: {
              reference: "Genesis 11:1–9",
              url: "https://www.churchofjesuschrist.org/study/scriptures/ot/gen/11.1-9",
            },
            lessonUrl:
              "https://www.churchofjesuschrist.org/study/manual/come-follow-me-for-home-and-church-old-testament-2026/07",
            question:
              "What was the main problem with the people’s desire to build the Tower of Babel?",
            options: [
              "They sought their own glory instead of God’s.",
              "They wanted to live together in unity.",
              "They were trying to worship God.",
              "They needed shelter from storms.",
            ],
            correctAnswer: 0,
            explanation:
              "Their project was driven by pride and a desire to ‘make a name’ for themselves, not to honor God.",
            references: [],
          },
        ],
      },
      {
        id: "week-07-day-7",
        date: "2026-02-15",
        doctrine: {
          doctrine: "God’s Covenant Continues Through Chosen Lineages",
          summary:
            "The genealogy from Shem to Abram prepares the way for the Abrahamic covenant.",
          explanation:
            "Genesis 11 concludes with the line of Shem leading to Abram. This shows that God’s covenant purposes continue through specific families, ultimately pointing to Jesus Christ and the blessings promised to all nations.",
          references: [],
          scriptures: [
            {
              reference: "Genesis 11:10–32",
              url: "https://www.churchofjesuschrist.org/study/scriptures/ot/gen/11.10-32",
            },
          ],
        },
        scripturePassage: {
          reference: {
            reference: "Genesis 11:27–32",
            url: "https://www.churchofjesuschrist.org/study/scriptures/ot/gen/11.27-32",
          },
          text: "A summary of the family of Terah, including Abram, Sarai, and Lot, and their move toward Canaan.",
          context:
            "The narrative transitions from the post-Flood world to the story of Abram, setting the stage for the Abrahamic covenant.",
          historicalBackground:
            "Ur and Haran were important cities in the ancient Near East; movement between them reflects trade and migration patterns of the time.",
          citations: [],
        },
        word: {
          id: "week-07-day-7-word",
          date: "2026-02-15",
          weekTitle: "The Covenant",
          word: "Lineage",
          definition:
            "A line of descent from an ancestor; in scripture, often tied to covenant responsibilities and blessings.",
          context:
            "The lineage from Shem to Abram prepares for the Abrahamic covenant.",
          scriptures: [
            {
              reference: "Genesis 11:27",
              url: "https://www.churchofjesuschrist.org/study/scriptures/ot/gen/11.27",
            },
          ],
        },
        questions: [
          {
            scriptureReference: {
              reference: "Genesis 11:27–32",
              url: "https://www.churchofjesuschrist.org/study/scriptures/ot/gen/11.27-32",
            },
            lessonUrl:
              "https://www.churchofjesuschrist.org/study/manual/come-follow-me-for-home-and-church-old-testament-2026/07",
            question:
              "Why is the genealogy from Shem to Abram important in the Old Testament?",
            options: [
              "It shows how God’s covenant purposes continue through chosen families.",
              "It is only a historical curiosity.",
              "It replaces the need for covenants.",
              "It shows that God stopped working with mankind.",
            ],
            correctAnswer: 0,
            explanation:
              "These verses connect the story of the Flood to Abram, through whom God will establish the Abrahamic covenant.",
            references: [],
          },
        ],
      },
    ],
    people: [
      {
        name: "Noah",
        role: "Prophet and patriarch",
        description:
          "A just man who walked with God, preached repentance, built the ark, and received a covenant from the Lord after the Flood.",
        scriptureReferences: [
          {
            reference: "Genesis 6–9",
            url: "https://www.churchofjesuschrist.org/study/scriptures/ot/gen/6",
          },
          {
            reference: "Moses 8",
            url: "https://www.churchofjesuschrist.org/study/scriptures/pgp/moses/8",
          },
        ],
        citations: [],
      },
      {
        name: "Shem",
        role: "Patriarchal ancestor",
        description:
          "One of Noah’s sons whose lineage leads to Abram and the covenant people.",
        scriptureReferences: [
          {
            reference: "Genesis 10:21–32",
            url: "https://www.churchofjesuschrist.org/study/scriptures/ot/gen/10.21-32",
          },
          {
            reference: "Genesis 11:10–11",
            url: "https://www.churchofjesuschrist.org/study/scriptures/ot/gen/11.10-11",
          },
        ],
        citations: [],
      },
      {
        name: "Hamitic and Japhethic Descendants",
        role: "Nations and families",
        description:
          "The descendants of Ham and Japheth represent many nations of the earth, showing the breadth of God’s family.",
        scriptureReferences: [
          {
            reference: "Genesis 10",
            url: "https://www.churchofjesuschrist.org/study/scriptures/ot/gen/10",
          },
        ],
        citations: [],
      },
      {
        name: "Builders of Babel",
        role: "Symbolic group",
        description:
          "A group united in prideful ambition to build a tower to heaven, whose language was confounded by the Lord.",
        scriptureReferences: [
          {
            reference: "Genesis 11:1–9",
            url: "https://www.churchofjesuschrist.org/study/scriptures/ot/gen/11.1-9",
          },
        ],
        citations: [],
      },
    ],
    places: [
      {
        name: "Ararat",
        modernLocation:
          "Region traditionally associated with the mountains of eastern Turkey or nearby Armenia",
        locationType: "probable",
        description: "The region where the ark came to rest after the Flood.",
        scriptureReferences: [
          {
            reference: "Genesis 8:4",
            url: "https://www.churchofjesuschrist.org/study/scriptures/ot/gen/8.4",
          },
        ],
        citations: [],
      },
      {
        name: "Babel",
        modernLocation:
          "Often associated with ancient Babylon in Mesopotamia (modern Iraq)",
        locationType: "probable",
        description:
          "The city where people attempted to build a tower to heaven and where the Lord confounded their language.",
        scriptureReferences: [
          {
            reference: "Genesis 11:1–9",
            url: "https://www.churchofjesuschrist.org/study/scriptures/ot/gen/11.1-9",
          },
        ],
        citations: [],
      },
      {
        name: "Ur of the Chaldees",
        modernLocation:
          "Generally identified with a city in southern Mesopotamia (modern southern Iraq)",
        locationType: "probable",
        description:
          "The homeland of Abram’s family mentioned at the end of Genesis 11, preparing for the Abrahamic story.",
        scriptureReferences: [
          {
            reference: "Genesis 11:28–31",
            url: "https://www.churchofjesuschrist.org/study/scriptures/ot/gen/11.28-31",
          },
        ],
        citations: [],
      },
    ],
  },
];
